apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xvancoa-ambulance-ufe-content
spec:
  microFrontend: xvancoa-ambulance-ufe
  element: xvancoa-ambulance-wl-app
  attributes:
    - name: base-path
      value: /xvancoa-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xvancoa-ambulance-wl(/.*)?$"